server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: user-authentication-service
          uri: lb://user-authentication-service
          predicates:
            - Path=/auth/**
        - id: order-processing-service
          uri: lb://order-processing-service
          predicates:
            - Path=/orders/**
        - id: inventory-management-service
          uri: lb://inventory-management-service
          predicates:
            - Path=/inventory/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
